ALTER TABLE profiles ADD COLUMN IF NOT EXISTS occupation VARCHAR(120);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS location VARCHAR(120);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS native_language VARCHAR(60);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS learning_language VARCHAR(60);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS language_level VARCHAR(60);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS match_purpose VARCHAR(120);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone_number VARCHAR(60);
