ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider VARCHAR NOT NULL DEFAULT 'email';
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_id VARCHAR NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_google_id_unique
ON users (google_id)
WHERE google_id IS NOT NULL;
